#!/usr/bin/env bash
# Script bash qui configure une nouvelle machine Ubuntu
apt-get update -y
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart