#!/usr/bin/env bash
# Le script bash qui fait que /redirect_me redirige vers une autre page.
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Ngnix HTTP'
echo "Hello World" >/var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=rWEocmYxFbc permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
