#!/usr/bin/env bash
# Configurez le serveur Nginx pour que /redirect_me redirige vers une autre page
# apt-get update -y
# apt-get install -y nginx
# echo "Hello World!" > /var/www/html/index.nginx-debian.html
# service nginx restart

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
bash -c 'echo Hello World > /var/www/html/index.nginx-debian.html'
sed -i '/^\s*server_name \_\;$/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
service nginx restart
