#!/usr/bin/env bash
# Installer et configurer HAproxy sur le serveur lb-01
apt -y update && upgrade -y;
apt install -y haproxy;
echo "frontend http
    bind *:80
    mode http
    default_backend web-backend
backend web-backend
    balance roundrobin
    server 3590-web-01	54.83.125.162:80 check
    server 3590-web-02	54.82.83.79:80 check" >> /etc/haproxy/haproxy.cfg;
service haproxy restart;
