#!/usr/bin/env bash
# debbug
# sources debug solution : https://stackoverflow.com/questions/16021481/nginx-not-listening-to-port-80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
