#!/usr/bin/env bash
# displays bad luck for 4th iteration and good luck for 8th, "Best School" for others
i=1
while [ $i -le 10 ]
do
    if [ $i == 4 ]
    then
	echo "bad luck"
    elif [ $i == 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    let i++
done
