#!/usr/bin/env bash
# displays number from 1-20 and displays bad luck for 4th, 9th, and 17th iteration.
i=1
while [ $i -le 20 ]
do
    echo "$i"
    case "$i" in
	4 )
	echo "bad luck from China";;
	9 )
	echo "bad luck from Japan";;
	17 )
	echo "bad luck from Italy";;
    esac
    let i++
done
