#!/usr/bin/env bash
#Comment
table=(
	"127.0.0.2 localhost"
	"8.8.8.8 facebook.com"
	)
str=""
longueur=${#table[@]}
longueur=$((longueur - 1))
cp /etc/hosts ~/hosts.new

for ((i=0; i<=longueur; i++))
do
	str+=${table[i]}
	if [ $i -lt $longueur ]
	then
		str+="\n"
	fi
done
sed -i "s/127.*$/$str/" ~/hosts.new
cp -f ~/hosts.new /etc/hosts