#!/usr/bin/env bash
# etape 1 filtrer les élement contenant inet
# etape 2 récuperer seulement les valeur numérique et les points
ifconfig | grep -oE 'inet\s([0-9]+\.?){4}' | grep -oE '([0-9]+\.?){4}'
