#!/usr/bin/env bash
# etape 1 filtrer les élement contenant inet
# etape 2 récuperer seulement les valeur numérique et les points
ifconfig | grep -Eo ' ([0-9]*.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*'
